// All functions accept the active transaction client (from withTransaction) so a
// sale, its items, the stock ledger, the inventory rollup, and the invoice outbox
// row all commit or roll back together.

export async function findSaleWithItems(client, { saleId, clientUuid }) {
  const where = saleId ? 'id = $1' : 'client_uuid = $1';
  const { rows } = await client.query(`SELECT * FROM sales WHERE ${where}`, [saleId ?? clientUuid]);
  const sale = rows[0];
  if (!sale) return null;
  const { rows: items } = await client.query(
    'SELECT * FROM sale_items WHERE sale_id = $1',
    [sale.id],
  );
  return { ...sale, items };
}

// Insert the sale; DO NOTHING on a replayed client_uuid so we can detect the replay.
export async function insertSale(client, s) {
  const { rows } = await client.query(
    `INSERT INTO sales
       (promoter_id, location_id, customer_id, invoice_no, payment_mode, total,
        whatsapp_status, in_radius, override_by, override_reason, client_uuid)
     VALUES ($1,$2,$3,$4,$5,$6,'pending',$7,$8,$9,$10)
     ON CONFLICT (client_uuid) WHERE client_uuid IS NOT NULL DO NOTHING
     RETURNING *`,
    [s.promoter_id, s.location_id ?? null, s.customer_id ?? null, s.invoice_no,
     s.payment_mode, s.total, s.in_radius ?? null, s.override_by ?? null,
     s.override_reason ?? null, s.client_uuid],
  );
  return rows[0] || null; // null => replay (already existed)
}

export async function insertSaleItem(client, it) {
  await client.query(
    `INSERT INTO sale_items (sale_id, product_id, qty, unit_price)
     VALUES ($1,$2,$3,$4)`,
    [it.sale_id, it.product_id, it.qty, it.unit_price],
  );
}

// Negative quantity = stock leaving. reference_id ties it back to the sale.
export async function insertStockDeduction(client, d) {
  await client.query(
    `INSERT INTO stock_transactions (promoter_id, product_id, type, quantity, reference_id)
     VALUES ($1,$2,'sale_deduction',$3,$4)`,
    [d.promoter_id, d.product_id, -Math.abs(d.qty), d.sale_id],
  );
}

// Daily stock cycle: add to today's "sold" (closing is generated by the DB).
export async function addInventorySold(client, inv) {
  await client.query(
    `INSERT INTO inventory (promoter_id, product_id, sold, day)
     VALUES ($1,$2,$3,current_date)
     ON CONFLICT (promoter_id, product_id, day)
     DO UPDATE SET sold = inventory.sold + EXCLUDED.sold`,
    [inv.promoter_id, inv.product_id, inv.qty],
  );
}

// Upsert the customer master by mobile (mobile is unique). Fills in the name if a
// new one is provided, keeping any existing name otherwise. Returns the id.
export async function upsertCustomer(client, { mobile, name }) {
  const { rows } = await client.query(
    `INSERT INTO customers (name, mobile, lead_source)
     VALUES ($1, $2, 'sale')
     ON CONFLICT (mobile) DO UPDATE SET name = COALESCE(EXCLUDED.name, customers.name)
     RETURNING id`,
    [name ?? null, mobile],
  );
  return rows[0].id;
}

export async function getCustomerMobile(client, customerId) {
  if (!customerId) return null;
  const { rows } = await client.query('SELECT mobile FROM customers WHERE id = $1', [customerId]);
  return rows[0]?.mobile || null;
}
